language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
- '10'
before_script:
- npm install -g @angular/cli
script:
- ng lint
- npm run test-headless
- ng e2e
- ng build --prod
deploy:
  provider: s3
  access_key_id: AKIA4C6ODJ7LW5SONXF7
  secret_access_key:
    secure: w148fFSaVAGwBbEx3juu+8QXlxbmJhUt9F3tFz3Q6ORKA+4Dg71lrKvpvJDtR3fCtr3RE6akhat+6I/ib5ktJNMiJzpLwgmKH6Qubk4UScHpISxT94iBBT1evRD9Rr5NeqwZ/Q+paD72mvI6bBqkebl6VSNJeaBaokZLnG3YLvWmPAVq7Ks606c1AjHv58Lj26qxHhz2JrMWiRC/XOsJ5pYJO2kJrOytTHp3/LME10J3T3OWuTxiWh0hVdmPK8S2uNlmPLCn6bswL3+XLs4pin+DPqt/WP51Hsmd3AviPN4yVhsqrMjOAPmd8WhspfClXmXqpNpcLLkupr5yBfn5o5qMuJ71S7rAP96Kd4m1bMQb2F8DH5nnjHQY/x78SvZ7yh5dC81aUCkKni6yQiHhe2LaqhOfzVr9r4kHlYKWd7h8dLafJe8rOrpOKzISWzsEOc0fPNEDxT09C8fBhxRJwEKWRSqN53gvU0tlzCvb4xko0+ZT/QKDABvlIzS/6naMSZ7+bpB1J+WadGTsjw9b8U2p2DYuVP5GNe/5d1VV7/c+U7E5Li33qz/5Xh85e68xPJR9ixE+Sb6UZtDl6ZyEZEcvFI8Zv+8omTNyaCZXq1muUDwxwur0fVFnklgR2dtr8wtjR4Ny9J78FVU0xUqNxCG93Y8SmaQmYcMV4j3q4c4=
  bucket: "auth-web-webtree"
  skip_cleanup: true
  region: eu-central-1
  local_dir: dist/auth-web
  acl: public_read
notifications:
  slack:
    secure: Keff3SyBZkZJ4CN063V9256q9666ldwyeNozQ1wsQPN5uN/VktvQkJr4lEg9ibp/Zj4kug7vHYSQmylgQTCPUiOD3l0NizxTrySy5f925tPIvk/7jDutzO3jeQoU0peY+nfJEsPaurZNDZDsMf8VwptVPfqMoe1HRXRVy2uP9jAAZ3ioyOWlRO/0XMNcJEFs1MXhxarx/EgcQ03CEhhcFhmj/OlWuRdRR9hCsmBA6r9FlHGnehYEZE4MPMQ2mnZDgVIZKlwwrG+73vzxERn0RBYq4cATrf8gug22X7JV24sXwV30MCocqP1UZGPgoZ2M3StE7HhNLTouGG10SZLoodJ5fLTn2zjfweRq8VJZaGh+XAYncIctKerD3ivNt5uIXIyz4GipEJH4MAsXQNhq5AxUkyN8LmwVm1gN3u4YkWMeAFZdOOKO0VOjlqMVraEXeJB9ejug4h+mBcdv07i3UWf4hKKxFvqFQCSTjNrjATiaSP4k2+koIEyw938DRBpBc6zrZawGKgBL6wWvJ6fXz0PAOHf2pWwcv43B1PDz7XrK/liKW5ev6U8JCv/80ebIBFOPyMY7FrMpxj66HhQBAxsH849ZlWlrq6UAZcVIp8ho74xk0a6QPtEN6do+WOYFzeyZ1JLoLAwh5eYu9+26WqTEAS+4wmaw3SAHO4Oj8bI=
