name: github-pages-deploy

on:
  push:	
    branches:	
      - master
      - gb-pages-deploy
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Wait for build to succeed
      uses: fountainhead/action-wait-for-check@1.0.0
      id: wait-for-build
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: build
        ref: github.event.pull_request.head.sha || github.sha
    - name: Deploy
      if: steps.wait-for-build.outputs.conclusion == 'success'
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npm run-script ng deploy -- --no-silent --cname=${{ secrets.AUTH_URL }}
