name: CI

on:
  push:	
    branches:	
      - master
      - gb-pages-deploy
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: |
        npm ci
        npm run-script ng deploy --no-silent --cname=${{ secrets.AUTH_URL }}
