name: github-pages-deploy

on:
  push:	
    branches:	
      - master
      - gb-pages-deploy
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Wait for status checks'
      id: waitforstatuschecks
      uses: "WyriHaximus/github-action-wait-for-status@f8bbe3bb321919ec6a009bc98121f39874dc8ee0"
      with:
        ignoreActions: github-pages-deploy
        checkInterval: 10
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Deploy
      if: steps.waitforstatuschecks.outputs.status == 'success'
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npm run-script ng deploy -- --no-silent --cname=${{ secrets.AUTH_URL }}
