name: github-pages-deploy

on:
  push:	
    branches:	
      - master
      - gb-pages-deploy
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npm run-script ng deploy -- --no-silent --cname=${{ secrets.AUTH_URL }}
