name: Node CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm install -g @angular/cli
        npm ci
        npm run test-headless
        ng lint
        ng build --prod
      env:
        CI: true
