on:
  push:
    branches: 
      - master
      - test

name: Bump version

jobs:
  tag-next-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: Bump version and push tag
        run: |
          git config --local user.email "cicd@webtree.org"
          git config --local user.name "Webtree CI/CD"
          npm version patch
          git push https://cicd-webtree:e6e941940286b967302f0b460e60dec802c68351@github.com/Web-tree/auth-web.git
          #git push --tags https://cicd-webtree:${{ secrets.CICD_GITHUB_TOKEN }}@github.com/Web-tree/auth-web.git
