on:
  push:
    branches: 
      - master
      - test-release

name: Bump version

jobs:
  tag-next-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        run: |
          git config --local user.email "cicd@webtree.org"
          git config --local user.name "Webtree CI/CD"
          npm version patch
          git push --tags
