name: web-deploy

on:
  release:
    types: [released]

jobs:
  web-deploy-prod:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Download release assets
      run: |
        wget ${{ github.event.release.assets[0].browser_download_url }}
        unzip auth-web.zip
    - name: Deploy at prod environment
      run: |
        npm i -g firebase-tools
        firebase use prod --token ${{ secrets.FIREBASE_PROD_TOKEN }}
        firebase deploy --only hosting:prod --token ${{ secrets.FIREBASE_PROD_TOKEN }}
